modLoader="javafml" 
loaderVersion="[37,)" 
license="All rights reserved"

[[mods]] 
modId="dolberhats" 
version="1.3" 
displayName="Non Craftable Items Become Craftable" 
logoFile=""
credits="Thanks to me for making this mod" 
authors="Love, Cheese and small house plants" 
description='''

IMPORTANT : Some crafts were not added because it would ruin the game, like adding the Elytra craft, 'cause then it would 
be pretty useless to go into the end realm to get all of its treasures if you can craft them in the OverWorld.
I hope you understand; Have a nice day :)

Ever dreamed of crafting an Ender Portal ? This is now possible. So just do it.

'''
[[dependencies.dolberhats]] 
    modId="forge" 
    mandatory=true 
    versionRange="[37.0.72,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.dolberhats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
