modLoader="javafml" 
loaderVersion="[41,)" 
license="All rights reserved"

[[mods]] 
modId="dragibussmaster" 
version="1.4" 
displayName="Non Craftable Objects Become Craftable" 
#logoFile=""
credits="Thanks to me for making this mod" 
authors="DragibussMaster" 

[[dependencies.dragibussmaster]] 
    modId="forge" 
    mandatory=true 
    versionRange="[41.1.0,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.dragibussmaster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
